name = "gaokao-english-grader"
main = "worker/index.ts"
compatibility_date = "2024-09-23"

# Bind the static assets (the built React app)
[assets]
directory = "./dist"
binding = "ASSETS"

# Use custom domain
[[routes]]
pattern = "eng.aryuki.com"
custom_domain = true

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "gaokao-en-grader-db"
database_id = "ea2e5dd2-682e-4fdb-89e3-668706ad39d1"

[vars]
API_DOMAIN = "generativelanguage.googleapis.com"
MODEL_NAME = "gemini-3-pro-preview"
LISTEN_MODEL_NAME = "gemini-3-flash-preview"
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "Mylover10"

# R2 Bucket binding
[[r2_buckets]]
binding = "R2"
bucket_name = "gaokao-english-server"

